spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user
  server:
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS}

broker:
  queue:
    email:
      name: default.email
