services:
  users-db:
    image: postgres:15
    container_name: users-postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  emails-db:
    image: postgres:15
    container_name: emails-postgres
    environment:
      POSTGRES_DB: emails_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - emails_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5555:80"
    depends_on:
      - users-db
      - emails-db
    networks:
      - microservices-network

volumes:
  users_data:
  emails_data:

networks:
  microservices-network:
    driver: bridge
