spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: email
  server:
    port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5433/emails_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS}
  mail:
    host: ${MAIL_SMTP}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
      name: default.email
