spring:
  application:
    name: email
  server:
    port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5433/emails_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: amqps://pflcoztb:Ljsi_J_R2YIuKAHxJbV20CsZJyVuT1yP@jaragua.lmq.cloudamqp.com/pflcoztb

broker:
  queue:
    email:
      name: default.email
